cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"

brew "git-lfs"
brew "mas"
brew "node"
brew "tree"

cask "adobe-acrobat-reader"
cask "atom"
cask "docker"
cask "firefox"
cask "forklift"
cask "google-chrome"
cask "opera"
cask "prefs-editor"
cask "skype"
cask "transmission"
cask "virtualbox"
cask "vlc"

mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
